# Site settings
email: liuxiaobaizone@sina.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Charlieroom
description: entertainment events,Life sharing,knowledge sharing
url: "charlieroom.top"
twitter_username: 
default_img: 

# Profile settings
name: The website of Andy and Charlie
profile_img: "/assets/images/profile.jpg"
profile: love and trust
social:
  github: 

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
